import http from './http';
import type {
  AiProviderConnectionTestResult,
  AiProviderModelListResponse,
  AiProviderType,
  AiSettingsResponse,
} from '@/types';

const AI_REQUEST_TIMEOUT_MS = 90000;

export const api = {
  login: (payload: { username: string; password: string }) => http.post('/auth/login', payload),
  me: () => http.get('/auth/me'),
  dashboard: () => http.get('/dashboard/overview'),
  settings: () => http.get('/settings'),
  updateSettings: (payload: unknown) => http.put('/settings', payload),
  knowledgeTree: () => http.get('/knowledge-points/tree'),
  createKnowledge: (payload: unknown) => http.post('/knowledge-points', payload),
  updateKnowledge: (id: number, payload: unknown) => http.put(`/knowledge-points/${id}`, payload),
  deleteKnowledge: (id: number) => http.delete(`/knowledge-points/${id}`),
  questions: (params?: Record<string, unknown>) => http.get('/questions', { params }),
  createQuestion: (payload: unknown) => http.post('/questions', payload),
  updateQuestion: (id: number, payload: unknown) => http.put(`/questions/${id}`, payload),
  deleteQuestion: (id: number) => http.delete(`/questions/${id}`),
  importQuestions: (formData: FormData) => http.post('/questions/import', formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  currentPlan: () => http.get('/plans/current'),
  generatePlan: () => http.post('/plans/generate'),
  updateTask: (id: number, payload: unknown) => http.patch(`/tasks/${id}`, payload),
  rebalanceTasks: (payload?: unknown) => http.post('/tasks/rebalance', payload ?? {}),
  createPracticeSession: (payload: unknown) => http.post('/practice/sessions', payload),
  getPracticeSession: (id: number) => http.get(`/practice/sessions/${id}`),
  submitPractice: (id: number, payload: unknown) => http.post(`/practice/sessions/${id}/submit`, payload),
  reviewPracticeRecord: (id: number, payload: unknown) => http.post(`/practice/records/${id}/review`, payload),
  updatePracticeFlags: (id: number, payload: unknown) => http.patch(`/practice/records/${id}/flags`, payload),
  mistakes: (params?: Record<string, unknown>) => http.get('/mistakes', { params }),
  updateMistake: (id: number, payload: unknown) => http.patch(`/mistakes/${id}`, payload),
  exams: () => http.get('/exams'),
  examAttempts: () => http.get('/exam-attempts'),
  createExam: (payload: unknown) => http.post('/exams', payload),
  startExam: (id: number) => http.post(`/exams/${id}/attempts`),
  getExamAttempt: (id: number) => http.get(`/exam-attempts/${id}`),
  submitExam: (id: number, payload: unknown) => http.post(`/exam-attempts/${id}/submit`, payload),
  scoreAfternoonExam: (id: number, payload: unknown) => http.post(`/exam-attempts/${id}/score-afternoon`, payload),
  notes: (params?: Record<string, unknown>) => http.get('/notes', { params }),
  createNote: (payload: unknown) => http.post('/notes', payload),
  updateNote: (id: number, payload: unknown) => http.put(`/notes/${id}`, payload),
  deleteNote: (id: number) => http.delete(`/notes/${id}`),
  analyticsSummary: () => http.get('/analytics/summary'),
  analyticsTrends: () => http.get('/analytics/trends'),
  exportAll: () => http.get('/export/full'),
  importAllBundle: (payload: unknown, strategy = 'OVERWRITE') => http.post(`/import/full?strategy=${strategy}`, payload),
  importAllFile: (formData: FormData, strategy = 'OVERWRITE') => http.post(`/import/full-file?strategy=${strategy}`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  aiProviders: () => http.get('/ai/providers'),
  aiModels: (params?: Record<string, unknown>) => http.get('/ai/models', { params }),
  aiSettings: () => http.get<AiSettingsResponse>('/ai/settings'),
  updateAiSettings: (provider: AiProviderType, payload: unknown) => http.put(`/ai/settings/${provider}`, payload),
  testAiSettings: (provider: AiProviderType, payload?: unknown) => http.post<AiProviderConnectionTestResult>(
    `/ai/settings/${provider}/test`,
    payload ?? {},
    { timeout: AI_REQUEST_TIMEOUT_MS },
  ),
  aiSettingsModels: (provider: AiProviderType) => http.get<AiProviderModelListResponse>(`/ai/settings/${provider}/models`),
  aiGenerateQuestions: (payload: unknown) => http.post('/ai/questions/generate', payload, { timeout: AI_REQUEST_TIMEOUT_MS }),
  aiSaveQuestions: (payload: unknown) => http.post('/ai/questions/save', payload),
  aiHistory: () => http.get('/ai/history'),
  aiHealth: () => http.get('/ai/health'),
  health: () => http.get('/health'),
};
