/**
 * Seed the OSE database from the 51CTO 软件设计师 historical exam dataset.
 *
 * This is the canonical seed for self-deployments — all 41 历年真题 are baked
 * into the binary via `data/51cto-seed.json`. Running `npm run db:seed` first
 * wipes any non-51CTO Exam/Question records (older demo content, AI-generated
 * questions linked to mock exams) and then upserts the 51CTO bank.
 *
 * Source data is regenerated by:
 *   python scripts/convert-51cto-to-seed.py
 *   python scripts/apply-51cto-classifications.py    # AI knowledge-point map
 */

import {
  PrismaClient,
  ExamSession,
  ExamSessionType,
  ExamType,
  QuestionType,
  CaseAnswerType,
} from '@prisma/client';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { allKnowledgePoints, FALLBACK_KP } from './knowledge-tree';

const prisma = new PrismaClient();

const SEED_PATH = path.resolve(process.cwd(), 'data/51cto-seed.json');
const EXAM_ID_PREFIX = 'exam-51cto-';

// ---------- Types (mirror data/51cto-seed.json) ----------

type SeedOption = { label: string; content: string; isCorrect: boolean };
type SeedSubQuestion = {
  sourceQuestionId: number;
  subNumber: number;
  content: string;
  answerType: keyof typeof CaseAnswerType;
  referenceAnswer: string;
  score: number;
  explanation: string;
  showTypeName: string;
};
type SeedQuestion = {
  sourceQuestionId?: number;
  questionNumber: number;
  type: keyof typeof QuestionType;
  content: string;
  difficulty: number;
  explanation: string;
  knowledgePointId: string;
  score?: number;
  showTypeName?: string;
  options?: SeedOption[];
  rawAnswer?: string[];
  caseScenario?: {
    background: string;
    figures: unknown;
    subQuestions: SeedSubQuestion[];
  };
};
type SeedExam = {
  sourceId: number;
  title: string;
  type: keyof typeof ExamType;
  session: keyof typeof ExamSession;
  year: number;
  month: number;
  kind: 'CHOICE' | 'CASE';
  timeLimit: number;
  totalScore: number;
  totalQuestions: number;
  questions: SeedQuestion[];
};
type SeedPayload = {
  metadata: Record<string, unknown>;
  knowledgePoints: Array<{ id: string; name: string; sortOrder: number; description?: string }>;
  exams: SeedExam[];
};

// ---------- Wipe helpers ----------

async function wipeNon51CTOContent() {
  console.log('Pruning non-51CTO content...');

  // Exams not from 51CTO: delete cascades into ExamQuestion / ExamAttempt /
  // ExamAnswer.
  const removedExams = await prisma.exam.deleteMany({
    where: { id: { not: { startsWith: EXAM_ID_PREFIX } } },
  });
  console.log(`  exams removed: ${removedExams.count}`);

  // Questions not linked to any 51CTO exam.
  // Use a single query so onDelete: Cascade clears options, case scenarios,
  // user answers and wrong notes attached to each.
  const orphans = await prisma.question.findMany({
    where: { examQuestions: { none: { exam: { id: { startsWith: EXAM_ID_PREFIX } } } } },
    select: { id: true },
  });
  if (orphans.length > 0) {
    await prisma.question.deleteMany({ where: { id: { in: orphans.map((o) => o.id) } } });
  }
  console.log(`  questions removed: ${orphans.length}`);
}

// ---------- Main ----------

async function main() {
  if (!fs.existsSync(SEED_PATH)) {
    throw new Error(
      `Seed file not found: ${SEED_PATH}\n` + `Run: python scripts/convert-51cto-to-seed.py`
    );
  }
  const payload = JSON.parse(fs.readFileSync(SEED_PATH, 'utf-8')) as SeedPayload;

  console.log(
    `Loading 51CTO seed: ${payload.exams.length} exams, ${payload.metadata.scopedQuestionRecordCount} question rows`
  );

  await wipeNon51CTOContent();

  // 1. Knowledge tree (parents + leaves) + uncategorized fallback
  console.log('Upserting knowledge tree...');
  for (const kp of allKnowledgePoints()) {
    await prisma.knowledgePoint.upsert({
      where: { id: kp.id },
      update: {
        name: kp.name,
        parentId: kp.parentId,
        sortOrder: kp.sortOrder,
        description: kp.description,
      },
      create: {
        id: kp.id,
        name: kp.name,
        parentId: kp.parentId,
        sortOrder: kp.sortOrder,
        description: kp.description,
      },
    });
  }
  await prisma.knowledgePoint.upsert({
    where: { id: FALLBACK_KP.id },
    update: {
      name: FALLBACK_KP.name,
      sortOrder: FALLBACK_KP.sortOrder,
      description: FALLBACK_KP.description,
    },
    create: {
      id: FALLBACK_KP.id,
      name: FALLBACK_KP.name,
      sortOrder: FALLBACK_KP.sortOrder,
      description: FALLBACK_KP.description,
    },
  });

  // 2. Exams + questions
  for (const [examIdx, seedExam] of payload.exams.entries()) {
    const examId = `${EXAM_ID_PREFIX}${seedExam.sourceId}`;
    const sessionType = (seedExam.session === 'AM' ? 'AM' : 'PM') as keyof typeof ExamSessionType;

    console.log(
      `[${examIdx + 1}/${payload.exams.length}] ${seedExam.title} ` +
        `(${seedExam.questions.length} ${seedExam.kind === 'CHOICE' ? 'choice' : 'scenarios'})`
    );

    const exam = await prisma.exam.upsert({
      where: { id: examId },
      update: {
        title: seedExam.title,
        type: ExamType[seedExam.type],
        session: ExamSessionType[sessionType],
        timeLimit: seedExam.timeLimit,
        totalScore: seedExam.totalScore,
      },
      create: {
        id: examId,
        title: seedExam.title,
        type: ExamType[seedExam.type],
        session: ExamSessionType[sessionType],
        timeLimit: seedExam.timeLimit,
        totalScore: seedExam.totalScore,
      },
    });

    await prisma.examQuestion.deleteMany({ where: { examId: exam.id } });

    for (const [qIdx, sq] of seedExam.questions.entries()) {
      const session = ExamSession[seedExam.session];

      const question = await prisma.question.upsert({
        where: {
          year_session_questionNumber: {
            year: seedExam.year,
            session,
            questionNumber: sq.questionNumber,
          },
        },
        update: {
          content: sq.content,
          type: QuestionType[sq.type],
          difficulty: sq.difficulty,
          explanation: sq.explanation,
          knowledgePointId: sq.knowledgePointId,
        },
        create: {
          content: sq.content,
          type: QuestionType[sq.type],
          difficulty: sq.difficulty,
          year: seedExam.year,
          session,
          questionNumber: sq.questionNumber,
          explanation: sq.explanation,
          knowledgePointId: sq.knowledgePointId,
        },
      });

      if (sq.type === 'CHOICE') {
        await prisma.questionOption.deleteMany({ where: { questionId: question.id } });
        if (sq.options && sq.options.length > 0) {
          await prisma.questionOption.createMany({
            data: sq.options.map((opt) => ({
              questionId: question.id,
              label: opt.label,
              content: opt.content,
              isCorrect: opt.isCorrect,
            })),
          });
        }
      } else if (sq.type === 'CASE_ANALYSIS' && sq.caseScenario) {
        await prisma.caseScenario.deleteMany({ where: { questionId: question.id } });
        await prisma.caseScenario.create({
          data: {
            questionId: question.id,
            background: sq.caseScenario.background,
            figures: (sq.caseScenario.figures ?? undefined) as never,
            subQuestions: {
              create: sq.caseScenario.subQuestions.map((sub) => ({
                subNumber: sub.subNumber,
                content: sub.content,
                answerType: CaseAnswerType[sub.answerType],
                referenceAnswer: sub.referenceAnswer,
                score: sub.score,
                explanation: sub.explanation,
              })),
            },
          },
        });
      }

      await prisma.examQuestion.create({
        data: {
          examId: exam.id,
          questionId: question.id,
          orderNumber: qIdx + 1,
        },
      });
    }
  }

  console.log('\nDone.');
  console.log(
    `  ${payload.exams.length} exams, ` +
      `${payload.metadata.scopedQuestionRecordCount} questions, ` +
      `${payload.metadata.scenarioCount} case scenarios.`
  );
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
